export const statuses = {
  event: [
    "Idea",
    "Planning",
    "Confirmed",
    "Registrations Open",
    "Completed",
    "Cancelled",
  ],
  attendance: [
    "Confirmed attending",
    "Likely attending",
    "Awaiting response",
    "Not attending",
    "Not asked",
  ],
  speaker: [
    "Not contacted",
    "Invitation to be sent",
    "Invited",
    "Follow-up required",
    "Confirmed",
    "Declined",
    "Withdrawn",
  ],
  poster: [
    "Draft requested",
    "In progress",
    "Ready for review",
    "Approved",
    "Published",
    "Not required",
  ],
  meeting: ["Planned", "Confirmed", "Completed", "Cancelled"],
  meetingType: [
    "Executive meeting",
    "Meeting with another organisation",
    "Other meeting",
  ],
  task: ["Not started", "In progress", "Blocked", "Complete"],
  priority: ["Low", "Normal", "High", "Urgent"],
  venue: [
    "Not started",
    "Requested",
    "Tentatively booked",
    "Confirmed",
    "Not required",
  ],
  checklist: ["Not started", "In progress", "Complete", "Not applicable"],
  funding: ["No", "Pending", "Confirmed", "N/A"],
  required: ["Unknown", "Yes", "No"],
  relationship: [
    "Organiser",
    "Co-host",
    "Sponsor",
    "Venue partner",
    "Promotional partner",
    "Other",
  ],
};
export const checklistGroups: Record<string, string[]> = {
  Registration: [
    "Registration required",
    "Registration page created",
    "Registrations open",
  ],
  Marketing: [
    "Event graphic/poster",
    "Email promotion",
    "Social media promotion",
    "Partner promotion",
  ],
  Operations: [
    "AV requirements confirmed",
    "Catering required",
    "Catering confirmed",
    "Photographer required",
    "Name tags required",
    "Run sheet completed",
  ],
};
export const templateSeeds: [string, number, string, string][] = [
  ["Agree event plan and approval", -30, "High", "President"],
  ["Confirm food budget", -60, "High", ""],
  ["Confirm venue and room booking", -60, "High", ""],
  ["Confirm speakers", -45, "High", ""],
  ["Finalise event programme and run sheet", -14, "High", ""],
  ["Set up event registration", -35, "High", ""],
  ["Posters", -35, "High", ""],
  ["Launch event publicity", -28, "High", ""],
  ["Spread poster to academics ahead of event", -21, "Normal", ""],
  ["Review registrations and attendee numbers", -7, "Normal", ""],
  ["Confirm equipment and event materials", -7, "High", ""],
  ["Confirm committee attendance and event-day roles", -5, "High", "President"],
  ["Complete final event checks", -3, "Urgent", ""],
  ["Send final attendee reminder", -2, "Normal", "Secretary"],
  ["Event-day setup and attendee check-in", 0, "Urgent", ""],
  ["Deliver event-day run sheet responsibilities", 0, "Urgent", ""],
  ["Send follow-up and thank-you messages", 2, "Normal", "Secretary"],
  ["Record attendance and event outcomes", 3, "Normal", "Secretary"],
  ["Hold event debrief", 7, "Normal", "President"],
];
